Babybaras' Jam!
texas-egads/mega-micro-2022 pull request #22
Opened 2022-12-24 05:46 UTC by KnockbackNemo

Babybaras

Laddie#6142, MaddieL#6256

2022-12-24 06:05 UTC, KnockbackNemo commented
I'm sorry, it appears that I changed the base files and project settings, but I don't know what I did to change them or how to change them back

2023-01-11 19:18 UTC, matthew-zhang-306 commented on Assets/7-Babybaras/Scripts/Lassoscript.cs
> +        public static AudioSource bugSounds = Managers.AudioManager.CreateAudioSource();
Would this still work if execution starts from a main menu, before starting up the minigames? This is a static field, which means that at time time this evaluates, Managers.AudioManager might be unset. Are you able to ensure that this works even if that is the case?

2023-01-11 19:18 UTC, matthew-zhang-306 requested changes
.

2023-01-11 21:31 UTC, KnockbackNemo commented on Assets/7-Babybaras/Scripts/Lassoscript.cs
> +        public static AudioSource bugSounds = Managers.AudioManager.CreateAudioSource();
Thanks for pointing that out! I don't know how to test or ensure that it will work, so I just removed the static audio sources and made new non-static ones in other classes instead.

2023-01-12 05:59 UTC, merged